linux/mm.h & linux/hugetlb.h: cann't annotate functions
The argument passed to the clang annotations needs to defined
before using them. In this following case we don't have a
lock instance to pass on as it is locally defined:

2080 static inline spinlock_t *pmd_lock(struct mm_struct *mm, pmd_t *pmd)
2081 {
2082         spinlock_t *ptl = pmd_lockptr(mm, pmd);
2083         spin_lock(ptl);
2084         return ptl;
2085 }

If we pass on the `ptl` lock instance to `__acquires_spinlock` then we
get the following warning:

/home/himanshu/clang-thread-safety-analysis/include/linux/mm.h:2080:90: error: use of undeclared identifier 'ptl'

https://github.com/ClangBuiltLinux/thread-safety-analysis/issues/28#issuecomment-496215839
Signed-off-by: Himanshu Jha <himanshujha199640@gmail.com>